// Nombre en español por selección (la DB guarda el nombre en inglés de SofaScore).
const ES: Record<string, string> = {
  Spain: "España",
  Argentina: "Argentina",
  France: "Francia",
  England: "Inglaterra",
  Brazil: "Brasil",
  Portugal: "Portugal",
  Colombia: "Colombia",
  Netherlands: "Países Bajos",
  Ecuador: "Ecuador",
  Croatia: "Croacia",
  Germany: "Alemania",
  Norway: "Noruega",
  Japan: "Japón",
  Türkiye: "Turquía",
  Uruguay: "Uruguay",
  Switzerland: "Suiza",
  Senegal: "Senegal",
  Belgium: "Bélgica",
  Mexico: "México",
  Paraguay: "Paraguay",
  Austria: "Austria",
  Morocco: "Marruecos",
  Canada: "Canadá",
  Australia: "Australia",
  Scotland: "Escocia",
  Iran: "Irán",
  "South Korea": "Corea del Sur",
  Algeria: "Argelia",
  Panama: "Panamá",
  Uzbekistan: "Uzbekistán",
  Czechia: "Chequia",
  USA: "Estados Unidos",
  Sweden: "Suecia",
  Jordan: "Jordania",
  Egypt: "Egipto",
  "Côte d'Ivoire": "Costa de Marfil",
  "DR Congo": "RD Congo",
  Tunisia: "Túnez",
  Iraq: "Irak",
  "Bosnia & Herzegovina": "Bosnia y Herzegovina",
  "New Zealand": "Nueva Zelanda",
  "Saudi Arabia": "Arabia Saudí",
  "Cabo Verde": "Cabo Verde",
  Haiti: "Haití",
  "South Africa": "Sudáfrica",
  Ghana: "Ghana",
  Curaçao: "Curazao",
  Qatar: "Catar",
};

/** Nombre en español de la selección (fallback al original). */
export function teamES(name: string): string {
  return ES[name] ?? name;
}
